version: '3'

services:

  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_DATABASE: profmaket
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./api/docker/db/data:/var/lib/mysql:rw
    ports:
        - "3307:3306"
