version: "3.3"

services:

  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_DATABASE: profmaket
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./api/docker/db/data:/var/lib/mysql:rw
    ports:
        - "3307:3306"
  php-fpm:
    image: webdevops/php-dev:8.1
    hostname: php-fpm
    volumes:
      - "./api/:/app"
    working_dir: "/app"
    depends_on:
      - mysql
  nginx:
    image: webdevops/nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "8888:80"
    volumes:
      - "./api/:/app"
    depends_on:
      - php-fpm