vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: '%app.path.work.images%'
            upload_destination: '%kernel.project_dir%/public/images/image'
            namer: 'Vich\UploaderBundle\Naming\OrignameNamer'
            delete_on_remove: true
            delete_on_update: true